export type UiLocale = "en" | "es" | "ja";

export const UI_LOCALE_NAMES: Record<UiLocale, string> = { en: "English", es: "Español", ja: "日本語" };

export const UI_TEXT = {
  en: {
    tagline: "One material, every reader.", workspace: "Workspace", newMaterial: "New material", history: "History", sidebarHint: "Create level-adjusted materials and return to completed work here.",
    homeSubtitle: "Create a new reading-level version", detected: (language: string, confidence: number) => `${language} detected ${confidence}%`, manualLanguage: (language: string) => `${language} selected manually`, teachingMaterial: "Teaching material", language: "Language", targetLevels: "Target levels", selectedLevels: (count: number) => `${count}/4 selected`, charactersNeeded: (count: number) => `${count} more characters required`, selectLevelRequired: "Select at least one target level.", starting: "Starting...", convertMaterial: "Convert material", startError: "Could not start simplification.",
    pastConversions: "Past conversions", noConversions: "No conversions yet", noConversionsHint: "Create a material to see its progress and completed versions here.", material: "Material", status: "Status", created: "Created", levelsComplete: (complete: number, total: number) => `${complete}/${total} levels complete`, untitledMaterial: "Untitled material", searchHistory: "Search materials", allStatuses: "All statuses", reuseMaterial: "Use as new material", noMatchingHistory: "No matching materials.",
    generatedVersions: "Generated versions", originalText: "Original material", simplifiedText: "Simplified version", questions: "Questions", export: "Export", loading: "Loading...", failedAfter: (attempt: number, max: number) => `This level failed after ${attempt}/${max} verification attempts.`, inProgress: (step: string, attempt: number, max: number) => `${step} in progress, attempt ${attempt}/${max}`, regenerateLevel: "Regenerate level", regenerating: "Regenerating...", readability: "Readability", inRange: "in range", nearMatch: "near match", target: "target", attempts: "attempts", factConsistency: "Fact consistency", retained: "Retained", simplified: "Simplified", lost: "Lost", keyPhrases: "Language focus", questionLabel: "Questions", statusName: (status: string) => ({ pending: "pending", processing: "processing", converting: "converting", verifying: "verifying", fact_checking: "fact checking", key_phrases: "language focus", completed: "completed", failed: "failed", partially_failed: "partially failed" }[status] || status), stepName: (step: string) => ({ convert: "conversion", verify: "verification", fact_check: "fact check", key_phrases: "language focus", questions: "questions" }[step] || step),
    comprehensionQuestions: "Comprehension questions", generatedMaterial: "Generated material", backToResults: "Back to results", questionsGenerating: "Questions are still being generated.", keyPhrase: "Language focus", answer: "Answer:", regenerateQuestion: "Regenerate question", questionRegenerating: "Regenerating...", loadQuestionsError: "Could not load questions.", regenerateQuestionError: "Could not regenerate this question.",
    exportWorksheet: "Export worksheet", worksheet: "LevelLens worksheet", levels: "Levels", notReady: "(not ready)", include: "Include", studentCopy: "Student copy", teacherCopy: "Teacher copy", keyPhraseBox: "Language focus", answerPage: "Answer page", preparingPdf: "Preparing PDF...", downloadPdf: "Download PDF", selectCompletedLevel: "Select a completed level to preview.", loadExportError: "Could not load export data.", createPdfError: "Could not create PDF.", showDetails: "Show details",
  },
  es: {
    tagline: "Un material para cada lector.", workspace: "Espacio de trabajo", newMaterial: "Nuevo material", history: "Historial", sidebarHint: "Crea materiales adaptados por nivel y vuelve aquí para consultar los trabajos terminados.",
    homeSubtitle: "Crea una nueva versión para un nivel de lectura", detected: (language: string, confidence: number) => `${language} detectado ${confidence}%`, manualLanguage: (language: string) => `${language} seleccionado manualmente`, teachingMaterial: "Material didáctico", language: "Idioma", targetLevels: "Niveles objetivo", selectedLevels: (count: number) => `${count}/4 seleccionados`, charactersNeeded: (count: number) => `Faltan ${count} caracteres`, selectLevelRequired: "Selecciona al menos un nivel objetivo.", starting: "Iniciando...", convertMaterial: "Convertir material", startError: "No se pudo iniciar la simplificación.",
    pastConversions: "Conversiones anteriores", noConversions: "Aún no hay conversiones", noConversionsHint: "Crea un material para ver aquí su progreso y sus versiones terminadas.", material: "Material", status: "Estado", created: "Creado", levelsComplete: (complete: number, total: number) => `${complete}/${total} niveles completados`, untitledMaterial: "Material sin título", searchHistory: "Buscar materiales", allStatuses: "Todos los estados", reuseMaterial: "Usar como material nuevo", noMatchingHistory: "No hay materiales que coincidan.",
    generatedVersions: "Versiones generadas", originalText: "Material original", simplifiedText: "Versión simplificada", questions: "Preguntas", export: "Exportar", loading: "Cargando...", failedAfter: (attempt: number, max: number) => `Este nivel falló después de ${attempt}/${max} intentos de verificación.`, inProgress: (step: string, attempt: number, max: number) => `${step} en curso, intento ${attempt}/${max}`, regenerateLevel: "Regenerar nivel", regenerating: "Regenerando...", readability: "Legibilidad", inRange: "dentro del rango", nearMatch: "aproximado", target: "objetivo", attempts: "intentos", factConsistency: "Coherencia factual", retained: "Conservado", simplified: "Simplificado", lost: "Omitido", keyPhrases: "Enfoque lingüístico", questionLabel: "Preguntas", statusName: (status: string) => ({ pending: "pendiente", processing: "en proceso", converting: "convirtiendo", verifying: "verificando", fact_checking: "verificación factual", key_phrases: "enfoque lingüístico", completed: "completado", failed: "fallido", partially_failed: "parcialmente fallido" }[status] || status), stepName: (step: string) => ({ convert: "conversión", verify: "verificación", fact_check: "verificación factual", key_phrases: "enfoque lingüístico", questions: "preguntas" }[step] || step),
    comprehensionQuestions: "Preguntas de comprensión", generatedMaterial: "Material generado", backToResults: "Volver a resultados", questionsGenerating: "Las preguntas todavía se están generando.", keyPhrase: "Enfoque lingüístico", answer: "Respuesta:", regenerateQuestion: "Regenerar pregunta", questionRegenerating: "Regenerando...", loadQuestionsError: "No se pudieron cargar las preguntas.", regenerateQuestionError: "No se pudo regenerar esta pregunta.",
    exportWorksheet: "Exportar hoja de trabajo", worksheet: "Hoja de trabajo de LevelLens", levels: "Niveles", notReady: "(no listo)", include: "Incluir", studentCopy: "Copia para estudiantes", teacherCopy: "Copia para docentes", keyPhraseBox: "Enfoque lingüístico", answerPage: "Página de respuestas", preparingPdf: "Preparando PDF...", downloadPdf: "Descargar PDF", selectCompletedLevel: "Selecciona un nivel terminado para obtener una vista previa.", loadExportError: "No se pudieron cargar los datos de exportación.", createPdfError: "No se pudo crear el PDF.", showDetails: "Ver detalles",
  },
  ja: {
    tagline: "一つの教材を、すべての読者へ。", workspace: "ワークスペース", newMaterial: "新しい教材", history: "履歴", sidebarHint: "読解レベルに合わせた教材を作成し、完了した作業をここから確認できます。",
    homeSubtitle: "新しい読解レベル版を作成", detected: (language: string, confidence: number) => `${language}を検出 ${confidence}%`, manualLanguage: (language: string) => `${language}を手動選択`, teachingMaterial: "教材テキスト", language: "教材の言語", targetLevels: "対象レベル", selectedLevels: (count: number) => `${count}/4 レベルを選択`, charactersNeeded: (count: number) => `あと ${count} 文字必要です`, selectLevelRequired: "対象レベルを1つ以上選択してください。", starting: "開始中...", convertMaterial: "教材を変換", startError: "変換を開始できませんでした。",
    pastConversions: "過去の変換", noConversions: "変換履歴はまだありません", noConversionsHint: "教材を作成すると、進捗と完了したバージョンをここで確認できます。", material: "教材", status: "状態", created: "作成日時", levelsComplete: (complete: number, total: number) => `${total}レベル中 ${complete}レベル完了`, untitledMaterial: "無題の教材", searchHistory: "教材を検索", allStatuses: "すべての状態", reuseMaterial: "新しい教材として使う", noMatchingHistory: "一致する教材はありません。",
    generatedVersions: "生成されたバージョン", originalText: "元の教材", simplifiedText: "変換した文章", questions: "問題", export: "出力", loading: "読み込み中...", failedAfter: (attempt: number, max: number) => `${attempt}/${max} 回の検証後、このレベルの処理に失敗しました。`, inProgress: (step: string, attempt: number, max: number) => `${step}を実行中 (${attempt}/${max} 回目)`, regenerateLevel: "レベルを再生成", regenerating: "再生成中...", readability: "読みやすさ", inRange: "目標範囲内", nearMatch: "近似達成", target: "目標", attempts: "回", factConsistency: "事実の整合性", retained: "保持", simplified: "簡略化", lost: "欠落", keyPhrases: "言語のポイント", questionLabel: "問題", statusName: (status: string) => ({ pending: "待機中", processing: "処理中", converting: "変換中", verifying: "検証中", fact_checking: "事実確認中", key_phrases: "言語ポイント抽出中", completed: "完了", failed: "失敗", partially_failed: "一部失敗" }[status] || status), stepName: (step: string) => ({ convert: "変換", verify: "検証", fact_check: "事実確認", key_phrases: "言語ポイント抽出", questions: "問題生成" }[step] || step),
    comprehensionQuestions: "確認問題", generatedMaterial: "生成された教材", backToResults: "結果へ戻る", questionsGenerating: "問題を生成しています。", keyPhrase: "言語のポイント", answer: "解答:", regenerateQuestion: "問題を再生成", questionRegenerating: "再生成中...", loadQuestionsError: "問題を読み込めませんでした。", regenerateQuestionError: "問題を再生成できませんでした。",
    exportWorksheet: "ワークシートを出力", worksheet: "LevelLens ワークシート", levels: "レベル", notReady: "(準備中)", include: "含める要素", studentCopy: "生徒用", teacherCopy: "教師用", keyPhraseBox: "言語のポイント", answerPage: "解答ページ", preparingPdf: "PDFを準備中...", downloadPdf: "PDFをダウンロード", selectCompletedLevel: "完了したレベルを選択してプレビューします。", loadExportError: "出力データを読み込めませんでした。", createPdfError: "PDFを作成できませんでした。", showDetails: "詳細を表示",
  },
} satisfies Record<UiLocale, Record<string, string | ((...args: never[]) => string)>>;
